# Generated by Django 3.1.7 on 2021-04-12 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=15, verbose_name='Categoria')),
                ('titulo', models.CharField(max_length=40, verbose_name='Titulo')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('contenido', models.CharField(max_length=320, verbose_name='Contenido')),
                ('image', models.ImageField(upload_to='blog', verbose_name='Imagen')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha Publicacion')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-fecha'],
            },
        ),
    ]
