# Generated by Django 3.1.7 on 2021-04-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='none', verbose_name='Link'),
            preserve_default=False,
        ),
    ]
