# Generated by Django 3.1.7 on 2021-04-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210414_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Publicacion'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blog/default.png', upload_to='blog', verbose_name='Imagen'),
        ),
    ]
