# Generated by Django 3.1.7 on 2021-04-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portafolio',
            options={'ordering': ['-fecha'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
