# Generated by Django 3.1.7 on 2021-04-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210412_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='image',
            field=models.ImageField(default='default.png', upload_to='portafolio'),
        ),
    ]
