# Generated by Django 3.1.7 on 2021-04-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210415_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='descripcion',
            field=models.TextField(max_length=250),
        ),
    ]
